### ISSUE TITLE
Work mode

### ISSUE THREAD

**Issue by Maxwell86** [jgriss/FusionSolarPy#11]
Hi,

First of all, thanks for developing this API!

I have a question: I would like to change the "work mode" of the home battery.

I've seen that there is a function "active_power_control" available. However, I wonder how to use it?
            "No limit": 0,                                 --> probably this is the default?
            "Zero Export Limitation": 5,          --> what happens in case of surplus energy?
            "Limited Power Grid (kW)": 6,       --> would this need an extra parameter, indicating the amount of kW?
            "Limited Power Grid (%)": 7,         --> would this need an extra parameter, indicating the percentage?
Are there some examples or more documentation about the function "active_power_control"?
Or maybe this function is not really what I need if I would like to change the work mode?

In the FusionSolar app, it is possible to (manually) change the parameter settings, including the work mode, of the battery. I wonder, does an API function exist? If not, would it be possible to create one?
(Btw, on the FusionSolar website, I haven't found how to manually change the parameter settings.)

Thanks in advance!

**Comment by jgriss** [comment]
Hi @Maxwell86 ,

Unfortunately, as far as I know, the web based interface is read-only. I'm not aware of any functions to change any settings.

Kind regards,
Johannes
