### ISSUE TITLE
Battery Data

### ISSUE THREAD

**Issue by rafaeluriarte** [jgriss/FusionSolarPy#2]
I was trying to retrieve the battery percentage but I could not find the data in the "plant_data". It shows only if it has the battery ("existEnergyStore") but not its charge. Do you know if this info is available? In the web interface it is...

**Comment by jgriss** [comment]
Hi @rafaeluriarte,

I believe that the charge (for the complete time frame) is stored in `chargePower`. That's where the web interface's graph seems to be getting the data from.

I've updated the `get_last_plant_data` function to also return this value.

Please let me know if it works as expected!

**Comment by rafaeluriarte** [comment]
Thank you very much for the effort. Unfortunately, I don't think it is the right variable:

It says: 

Last battery charge at 2022-04-29 21:40: 0.0

But I am at 96%

![image](https://user-images.githubusercontent.com/19567189/166058965-d5f71ca8-2610-41e4-a79d-44656f877db4.png)

Any idea?

Thanks!

**Comment by jgriss** [comment]
Hi @rafaeluriarte 

Since I don't have a battery myself, it took a while to figure out. The data for this diagram is part of the energy flow.

I've added a function to get the complete data of this diagram:

```python
energy_flow = client.get_plan_flow(plant_id)
```

It's currently only on GitHub since I still want to add some nicer functions to process this data structure.

**Comment by rafaeluriarte** [comment]
Thanks a million, it works like a charm!

The data structure is a bit strange but we can get the battery percentage with
battery = energy_flow['data']['flow']['nodes'][4]['deviceTips']['SOC']

If you need some help with the dev, just let me know
