### ISSUE TITLE
Make it installable via pipx / pipsi

### ISSUE THREAD

**Issue by iranzo** [jgriss/FusionSolarPy#21]
created virtual environment CPython3.12.0.final.0-64 in 675ms
  creator CPython3Posix(dest=/home/iranzo/.local/venvs/fusion-solar-py, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(extra_search_dir=/usr/share/python-wheels,download=False, pip=bundle, via=copy, app_data_dir=/home/iranzo/.local/share/virtualenv)
    added seed packages: pip==23.3.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Collecting fusion_solar_py
  Using cached fusion_solar_py-0.0.17-py3-none-any.whl.metadata (14 kB)
Collecting requests>=2.31.0 (from fusion_solar_py)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.31.0->fusion_solar_py)
  Using cached charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests>=2.31.0->fusion_solar_py)
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.31.0->fusion_solar_py)
  Using cached urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests>=2.31.0->fusion_solar_py)
  Using cached certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Using cached fusion_solar_py-0.0.17-py3-none-any.whl (18 kB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Using cached charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, fusion_solar_py
Successfully installed certifi-2023.11.17 charset-normalizer-3.3.2 fusion_solar_py-0.0.17 idna-3.6 requests-2.31.0 urllib3-2.1.0
Did not find any scripts.  Uninstalling.

**Comment by jgriss** [comment]
Hi @iranzo 

Both `pipx` and `pipsi` are meant to install python *applications* in isolated environments.

`fusion_solar_py` is just a python library that can be used by other applications. That's why the installation fails.
