### ISSUE TITLE
Weird data Received from the new subdomains

### ISSUE THREAD

**Issue by mtziortzis** [jgriss/FusionSolarPy#24]
First off, thanks for this great library. I was using this just fine until i got migrated to the new subdomain. The data i receive now are a bit off.
I verified:
- i receive the right plant id (double checked with the url while i am logged in)
- i have the right subdomain (new one)

Here is the response i am getting from the `fsclient.get_last_plant_data(plant)`

{'onGridPowerRatio': None, 'selfUsePower': {'time': '2024-02-11 13:03', 'value': None}, 'selfUsePowerRatioByUse': None, 'existInverter': True, 'totalBuyPower': None, 'existEnergyStore': False, 'totalProductPower': 25.67, 'existIrradiation': False, 'dischargePower': {'time': '2024-02-11 13:03', 'value': None}, 'radiationDosePower': {'time': '2024-02-11 13:03', 'value': None}, 'mainsUsePower': {'time': '2024-02-11 13:03', 'value': None}, 'buyPowerRatio': None, 'selfUsePowerRatioByProduct': None, 'totalSelfUsePower': None, 'chargePower': {'time': '2024-02-11 13:03', 'value': None}, 'existCharge': False, 'existMeter': False, 'onGridPower': {'time': '2024-02-11 13:03', 'value': None}, 'dieselProductPower': {'time': '2024-02-11 13:03', 'value': None}, 'disGridPower': {'time': '2024-02-11 13:03', 'value': None}, 'selfProvide': None, 'productPower': {'time': '2024-02-11 13:03', 'value': None}, 'usePower': {'time': '2024-02-11 13:03', 'value': None}, 'meterActivePower': {'time': '2024-02-11 13:03', 'value': None}, 'totalUsePower': 25.67, 'chargeAndDisChargePower': {'time': '2024-02-11 13:03', 'value': None}, 'existUsePower': False, 'totalOnGridPower': None}

The actual values of totalProductPower and also the value of `stats.current_power_kw` are way off.

Is there anything else i should try ?
Notice all the 'None' values - i assume that is not right

**Comment by remedix** [comment]
any ideas @jgriss  ? :)

**Comment by mtziortzis** [comment]
Hi @jgriss 
Thank you for taking some time to look into this.

I think it comes down to state results. Let me explain.

In the current dashboard of fusionsolar there are two sets of data. The Plant KPIs (which seems to be off (delayed?) as shown here:
<img width="405" alt="Screenshot 2024-03-11 at 9 57 04 AM" src="https://github.com/jgriss/FusionSolarPy/assets/101566031/8ae17151-f0c2-4b80-ba0b-7397be9c8172">

And the almost realtime data shown here:
<img width="447" alt="Screenshot 2024-03-11 at 9 57 10 AM" src="https://github.com/jgriss/FusionSolarPy/assets/101566031/baa47075-9f59-4c2c-9169-d2b4ddaccb84">

The method `fsclient.get_power_status()` gets the first data (Plant KPIs) - the 'stale' ones

However the API endpoint `uni003eu5.fusionsolar.huawei.com/rest/pvms/web/station/v1/overview/station-real-kpi` seems to have the latest (real time) ones.

I tried the following from the browser
- clear cache
- clear cookies
- clear local storage

Nothing seems to be changing the stale data so they must be coming from the server. 

I think `fsclient.get_power_status()` should get the data from the endpoint as explained above - this will ensure the latest data. I hope this steers you to the right direction.

**Comment by jgriss** [comment]
Hi @mtziortzis ,

Sorry, time available for the project is a bit irregular...

Your observation is correct, the numbers shown in the overview seem to be stale.

Yet, you can already get the up-to-date data shown in the table using the `get_plant_stats` function combined with `get_last_plant_data`.

There, the `productPower` slot corresponds to the current production value.

**Comment by jgriss** [comment]
Sorry, just read the first part of your message. In my tests, the values shown in the table and the ones in get_last_plant data match. I'll check how I can support the new endpoint though

**Comment by jgriss** [comment]
Hi,

A second update: The more up-to-date data is also available in the station list which you can retrieve using `get_station_list`

**Comment by jgriss** [comment]
@mtziortzis I've added a new function `get_current_plant_data` in version 0.0.24 that uses the new endpoint.
