### ISSUE TITLE
It seems that some URLs have change

### ISSUE THREAD

**Issue by ATNALDC** [jgriss/FusionSolarPy#27]
Hi,

Since yesterday I get some errors. After investigating the origin, I have seen that some URL's seems to be discontinued and 
the REST API seems to be changed.

For example if I go to the url used to get plant list (https://uni003eu5.fusionsolar.huawei.com/rest/pvms/web/station/v1/station/station-list) I get 404 error. It also happens with device list. As I can find any REST documentation I can't investigate more.

Could you please check it?

Thank you very much;
Best regards,

**Comment by karstenBriksoft** [comment]
I’m not sure if this is a problem with logging in or with the subdomain. But on the webpage the urls seem to work, but they use different subdomains than the python code.

**Comment by jgriss** [comment]
Hi,

Some issues were related to the new encrypted login procedure (see #30)

This was solved in the most recent version (v0.0.26)

Getting the station list works in my unit tests. Could you check whether the error persists?

**Comment by ATNALDC** [comment]
It's solved with latest version.
