### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by IvRogoz** [jgriss/FusionSolarPy#28]
Since middle of last week Im unable to authenticate on Fusion.

AuthenticationException: Failed to login into FusionSolarAPI: None

Any idea why?

Update: Moved to uni001eu5

**Comment by denimmonkey** [comment]
I am having the same issue since the last week 

My domain is also 'uni001eu5'

**Comment by denimmonkey** [comment]
The error comes  for the function get_station_list, get_plant_stats still works 
```
ERROR: Failed to reset session and login again.
Login apparently failed. Received invalid response.


```

**Comment by Jongonzale** [comment]
In my case I'm getting the error also with the get_plant_ids method

**Comment by fvillemin** [comment]
Same error here, plant stats are available but other methods give
Login apparently failed. Received invalid response.

**Comment by thematt87** [comment]
I get also 470 error code on login on `uni002eu5`

**Comment by Jongonzale** [comment]
How you can know the plant id without the get_plant_ids method? Some said that it's that method the one that fails but that you can reach the info with other methods. I need the id

**Comment by jgriss** [comment]
Hi! This is the same issue as #29 

I'll update #29 with more information
